version: "3"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/bostongene_computations
    ports:
      - "8000:8000"
    depends_on:
      - db
  compute:
    build:
      context: .
      dockerfile: compute/Dockerfile
    command: python compute.py
    volumes:
      - .:/bostongene_computations
    depends_on:
      - db
